"""
The IdleRPG Discord Bot
Copyright (C) 2018-2021 Diniboy and Gelbpunkt
Copyright (C) 2024 Lunar (discord itslunar.)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

"""
The IdleRPG Discord Bot
Copyright (C) 2018-2021 Diniboy and Gelbpunkt
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from utils import random

items = [
    # Existing items
    ("Half-eaten Sandwich", 42),
    ("Invisible Hat", 0),
    ("Bag of Nothing", 1),
    ("Rubber Chicken", 123),
    ("Left Sock", 13),
    ("Right Sock", 13),
    ("Bucket of Steam", 999),
    ("Unicorn's Leftovers", 77),
    ("Expired Coupon", 5),
    ("Imaginary Friend", 1000),
    ("Square Wheel", 314),
    ("Chocolate Teapot", 273),
    ("Waterproof Towel", 666),
    ("Glass Hammer", 888),
    ("Inflatable Dartboard", 999),
    ("Anvil-shaped Balloon", 500),
    ("Solar-powered Flashlight", 250),
    ("Screen Door Submarine", 777),
    ("Glow-in-the-Dark Sunglasses", 333),
    ("Pet Rock", 10),
    ("Jar of Pickled Dreams", 555),
    ("Portable Hole", 800),
    ("Reusable Bubble Wrap", 90),
    ("One-time Use Ice Cube", 2),
    ("Self-Help Book for Dummies", 150),
    ("World's Smallest Giant", 7000),
    ("Honest Politician", 50000),
    ("Cat's Meow", 1234),
    ("Dog's Breakfast", 4321),
    ("Can of Dehydrated Water", 99),
    ("Left-handed Pencil", 11),
    ("Anti-Gravity Boots", 4200),
    ("Keyboard Without Keys", 404),
    ("Wi-Fi Toaster", 2020),
    ("Bacon-scented Air Freshener", 300),
    ("Squeaky Hammer", 101),
    ("Invisible Ink Pen", 0),
    ("Square Circle", 9999),
    ("Time-traveling Watch", 10000),
    ("Digital Analog Clock", 606),
    ("Unstoppable Force", 50000),
    ("Immovable Object", 50000),
    ("Schrödinger's Cat", 50),
    ("Bag of Dragon Breath", 8000),
    ("Bottomless Pit", 5000),
    ("Chocolate-covered Anchovies", 200),
    ("Magic 8-Ball That Only Says 'Maybe'", 888),
    ("Weather-Control Umbrella", 6000),
    ("Self-driving Bicycle", 1200),
    ("Voice-activated Book", 250),
    ("Glow-in-the-Dark Lightbulb", 100),
    ("Waterproof Sponge", 75),
    ("Edible Socks", 215),
    ("Zero-calorie Doughnut", 150),
    ("Remote-controlled Broom", 350),
    ("Solar-powered Nightlight", 400),
    ("Universal Remote (Doesn't Control Anything)", 250),
    ("Reversible Dice", 60),
    ("Unbreakable Bubble", 500),
    ("Endless Storybook (Never Finishes)", 700),
    ("Chocolate Fireguard", 50),
    ("Inflatable Anchor", 125),
    ("Swiss Cheese Plant (Actually Swiss Cheese)", 220),
    ("Wind-powered Fan", 330),
    ("Book of Unspeakable Words", 444),
    ("Map to Nowhere", 555),
    ("Two-wheeled Tricycle", 666),
    ("Anti-invisibility Cloak", 777),
    ("Giggle Stick", 88),
    ("Bagpipes of Silence", 999),
    ("Feather of Lead", 111),
    ("Everlasting Ice Cream (Always Melts)", 200),
    ("Mood Ring That Always Shows 'Confused'", 175),
    ("Bottomless Coffee Cup (Always Empty)", 300),
    ("Left-handed Screwdriver", 130),
    ("Bluetooth Toaster", 1400),
    ("Do-it-yourself Parachute Kit (Contains Napkin)", 50),
    ("Square Ball", 314),
    ("World's Smallest Violin", 60),
    ("Non-stick Glue", 120),
    ("Battery-powered Battery Charger", 600),
    ("Cat-proof Mouse", 250),
    ("Hitchhiker's Towel", 42),
    ("Infinite To-do List", 99),
    ("Invisible Bicycle", 500),
    ("Can of Wormholes", 7000),
    ("Unopenable Jar", 80),
    ("Unloseable Keys (Already Lost)", 100),
    ("Bag of Holding Other Bags", 250),
    ("Magic Mirror That Insults You", 450),
    ("Underwater Hairdryer", 550),
    ("Voice-activated Mute Button", 650),
    ("Anti-gravity Feather", 850),
    ("One-size-fits-none Hat", 150),
    ("Echo-less Canyon in a Bottle", 950),
    ("Ear Plugs That Amplify Sound", 115),
    ("Dictionary Without Words", 215),
    ("Disappearing Ink - Disappeared", 0),
    ("Self-folding Origami", 350),
    ("Do Not Press Button (Already Pressed)", 75),
    ("Infinite Wallpaper (Repeats Every Meter)", 125),
    ("Cursed Good Luck Charm", 666),
    ("Bottle of Fog", 180),
    ("Square Root of -1 Apples", 42),
    ("Hairless Wig", 60),
    ("Sour Sugar Cubes", 70),
    ("Gravity-resistant Apple", 300),
    ("Imitation Fake Mustache", 90),
    ("Bag of Lost Marbles", 200),
    ("Jam-less Printer (Always Out of Ink)", 400),
    ("Chocolate Teacup", 85),
    ("Self-tying Shoelaces (Knots Impossible to Untie)", 250),
    ("Book of 1000 Blank Pages", 500),
    ("Swiss Army Knife with No Tools", 350),
    ("Upside-down Compass", 275),
    ("Perpetual Motion Machine (Doesn't Work)", 1000),
    ("World's Loudest Silent Alarm Clock", 175),
    ("Eternal Flame Candle (Never Lights)", 150),
    ("Infinite Monkey Typewriter", 50000),
    ("Square Donut", 200),
    ("Invisible Sculpture", 25000),
    ("Genuine Faux Diamond", 5000),
    ("Life-sized Miniature", 7500),
    ("Non-alcoholic Whiskey", 120),
    ("Wireless Extension Cord", 800),
    ("Gluten-free Water", 2),
    ("Unicorn Horn Replica", 3000),
    ("Realistic Fake Beard", 400),
    ("Miniature Giant Space Hamster", 3000),
    ("Scentless Perfume", 100),
    ("Chocolate Kettle", 250),
    ("Upside-down Reading Glasses", 333),
    ("World's Heaviest Feather", 777),
    ("Inflatable Puncture Repair Kit", 150),
    ("Voice-activated Silent Alarm", 200),
    ("One-handed Clapping Gloves", 123),
    ("Battery-operated Solar Panel", 350),
    ("Instant Water (Just Add Water)", 50),
    ("Cat's Pajamas", 900),
    ("Monkey's Uncle", 1500),
    ("Barking Cat", 500),
    ("Meowing Dog", 500),
    ("Snowman Kit (Contains Carrot)", 5),
    ("Fireproof Matches", 75),
    ("World's Fastest Snail", 2000),
    ("Rubber Band Ball of Yarn", 220),
    ("Paperweight Made of Paper", 10),
    ("Edible Cookbook", 600),
    ("Honesty Potion", 4000),
    ("Bottle of Bottled Bottles", 300),
    ("World's Tallest Short Person", 7000),
    ("Earworm Removal Kit", 250),
    ("Inflatable Pin Cushion", 125),
    ("Invisible Paint", 0),
    ("Self-cleaning Mop", 900),
    ("Universal Adapter for Parallel Universes", 48000),
    ("Anti-time Stopwatch", 25000),
    ("Schrödinger's Gift Box (Contains Cat)", 49999),
    ("Interdimensional Pocket Lint", 10000),
    ("Quantum Leapfrog Game", 15000),
    ("Infinite Pie (Never Ends)", 31415),
    ("Black Hole in a Jar", 50000),
    ("Time-Delayed Instant Coffee", 800),
    ("Bag of Infinite Breadsticks (Olive Garden)", 1000),
    ("Pandora's Lunchbox", 27000),
    ("String Theory String", 16000),
    ("42nd Answer to Everything", 42000),
    ("Multiverse Map (Incomplete)", 35000),
    ("Antimatter Paperweight", 50000),
    ("Fourth-Dimensional Cube (Tesseract)", 30000),
    ("Hyperspace Bypass Plans", 15000),
    ("Uncertainty Principle Manual", 20000),
    ("Warp Drive Starter Kit", 50000),
    ("Cosmic Microwave Background Detector", 40000),
    ("Gravity Manipulator (Slightly Broken)", 38000),

    # New items added
    ("Self-Inflating Balloon (Doesn't Inflate)", 150),
    ("Leftover Leftovers", 25),
    ("Non-Stick Tape", 80),
    ("Infinite Loop Rope", 500),
    ("Unbreakable Rubber Band (Already Broken)", 60),
    ("One-Size-Fits-All Gloves (Too Small)", 120),
    ("Waterproof Tea Bag", 30),
    ("Underwater Candle", 300),
    ("Reusable Disposable Camera", 200),
    ("Silent Alarm Clock (Never Rings)", 90),
    ("Anti-Gravity Pen (Floats Away)", 250),
    ("Solar-Powered Moon Lamp", 400),
    ("Time-Traveling Postcard (From Tomorrow)", 1000),
    ("Self-Driving Skateboard", 800),
    ("Invisible Dog Leash", 70),
    ("Pet Rock Trainer's Manual", 40),
    ("World's Smallest Bigfoot Photograph", 3500),
    ("Square Hula Hoop", 200),
    ("Inflatable Dart", 50),
    ("Chocolate Oven (Melts Itself)", 500),
    ("Edible Calculator", 150),
    ("Non-Reflective Mirror", 0),
    ("Zero-Gravity Paperweight", 600),
    ("Upside-Down Umbrella", 220),
    ("Unspillable Cup (Always Empty)", 100),
    ("Invisible Book of Invisibility", 5000),
    ("Inverted Light Bulb (Makes Darkness)", 700),
    ("Endless Matchstick (Never Lights)", 75),
    ("Portable Hole Puncher", 125),
    ("Multi-Functional Single-Use Tool", 175),
    ("Magic Beans (Ordinary Beans)", 5),
    ("Inflatable Pin", 45),
    ("Gravity-Defying Feather (Falls Up)", 800),
    ("Weather Predictor (Always Wrong)", 250),
    ("One-Wheeled Bicycle", 300),
    ("Transparent Playing Cards", 150),
    ("Non-Electric Electric Guitar", 600),
    ("Soundproof Bell", 90),
    ("Liquid Ice", 20),
    ("Anti-Aging Cream (Expired)", 35),
    ("One-Time Use Reusable Bag", 60),
    ("Manual Book on How to Read", 200),
    ("Double-Sided Coin (Both Tails)", 110),
    ("Solar-Powered Candle", 80),
    ("Disappearing Rope Trick (No Rope Included)", 500),
    ("Non-Magnetic Magnet", 70),
    ("Instant Weight Loss Plan (Remove Shoes)", 25),
    ("World's Quietest Accordion", 300),
    ("Inflatable Fire Extinguisher", 120),
    ("Self-Opening Can Opener", 200),
    ("Remote-Controlled Book", 150),
    ("Magic Carpet (Stain Resistant)", 4000),
    ("Time-Stopping Watch (Doesn't Work)", 2500),
    ("Edible Toothbrush", 90),
    ("One-Way Window (Can't See Through Either Side)", 700),
    ("Unmelting Ice Cream (Always Frozen)", 500),
    ("Multi-Colored Invisible Ink Pens", 0),
    ("Reusable Candle Wick (Never Burns)", 75),
    ("Waterproof Kettle", 120),
    ("Non-Digital Smartwatch", 220),
    ("Underwater Bicycle", 600),
    ("Left-Handed Coffee Mug", 30),
    ("Upside-Down Map", 180),
    ("Inflatable Snowman (For Summer)", 250),
    ("Non-Stick Sticky Notes", 15),
    ("Cat-Flavored Dog Food", 40),
    ("Dog-Flavored Cat Food", 40),
    ("Unbreakable Bubble Wrap", 80),
    ("Ant Farm Without Ants", 60),
    ("Silent Drum Kit", 350),
    ("Caffeinated Coffee Mug (No Coffee Needed)", 150),
    ("Bulletproof Paint", 700),
    ("Magic Eraser (Erases Itself)", 100),
    ("Wireless Wire", 300),
    ("Portable Desktop", 500),
    ("Gravity-Enhanced Paperweight", 25),
    ("Time-Delayed Alarm Clock", 110),
    ("Inflatable Hammer", 65),
    ("Non-Reversible Reversible Jacket", 80),
    ("Self-Driving Unicycle", 400),
    ("Battery-Powered Battery", 50),
    ("Zero-Calorie Sugar", 5),
    ("Virtual Reality Book", 35),
    ("Inflatable Safety Pin", 70),
    ("Self-Deflating Balloon", 30),
    ("One-Color Rubik's Cube", 20),
    ("Left-Handed Hammer", 90),
    ("Invisible Earphones", 150),
    ("Non-Glare Light Bulb", 40),
    ("Disposable Reusable Straw", 10),
    ("Perpetual Calendar (Only Goes to 2020)", 200),
    ("Unbreakable Pencil Lead", 25),
    ("Cat Hair Sweater", 120),
    ("Invisible Bicycle Helmet", 0),
    ("Inflatable Doorstop", 55),
    ("Edible Soap", 70),
    ("Noise-Canceling Earplugs (Amplify Sound)", 110),
    ("Non-Reflective Sunglasses", 90),
    ("World's Smallest Large Soda", 2),
    ("Square Balloon", 15),
    ("Voice-Activated Echo", 75),
    ("Scentless Air Freshener", 5),
    ("Self-Closing Door (Always Closed)", 250),
    ("Zero-Gravity Chair (Floats Away)", 800),
    ("Magic Wand (Just a Stick)", 10),
    ("Battery-Operated Candle", 30),
    ("Non-Absorbent Sponge", 15),
    ("Pet Brick", 5),
    ("Inflatable Safety Vest (Deflates Quickly)", 150),
    ("Inverted Compass (Points South)", 120),
    ("Soundless Speaker", 300),
    ("Endless Bubble Gum (Loses Flavor Instantly)", 40),
    ("Time-Traveling DeLorean (Out of Gas)", 45000),
    ("Bag of Infinite Breadsticks (Olive Garden)", 1000),
    ("Unopenable Can of Worms", 90),
    ("Infinite Bookmark (Never Finds Your Page)", 35),
    ("Multi-Tasking Toaster (Only Toasts Bread)", 80),
    ("Anti-Gravity Coffee Mug (Floats Away When Empty)", 150),
    ("Wireless Keyboard (Missing Keys)", 70),
    ("Self-Aware Pillow (Keeps You Awake)", 200),
    ("Teleporting Frisbee (Never Returns)", 300),
    ("Echoing Earplugs (Amplifies Noise)", 120),
    ("Double-Sided Notebook (Both Sides Blank)", 50),
    ("Left-Handed Scissors (For Right-Handed People)", 60),
    ("Non-Slip Banana Peel", 25),
    ("Magic Potion (Just Colored Water)", 15),
    ("Gravity-Challenged Yo-Yo", 100),
    ("World's Largest Tiny Hat", 250),
    ("Edible Remote Control (Not Recommended)", 110),
]


# The combined list contains all the items from both lists



def get_item(adventure_level: int = 1) -> dict[str, str | int]:
    """Get a random item based on adventure level.
    
    Args:
        adventure_level: The level of the adventure (1-100)
        
    Returns:
        dict: Item with name and value
    """
    # Calculate the minimum value threshold based on adventure level
    # At level 1: 0% of max value
    # At level 100: 90% of max value
    min_value_threshold = (adventure_level / 100) * 0.9
    
    # Get max value from all items
    max_value = max(item[1] for item in items)
    
    # Calculate minimum value for this adventure level
    min_value = int(max_value * min_value_threshold)
    
    # Filter items that are at or above the minimum value
    eligible_items = [item for item in items if item[1] >= min_value]
    
    # If no items meet the criteria (shouldn't happen), use all items
    if not eligible_items:
        eligible_items = items
    
    # Randomly select an item from eligible items
    item = random.choice(eligible_items)
    return {"name": item[0], "value": item[1]}
